apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab901 
  labels:
    app: frontend-lab901 
spec:
  selector:
    matchLabels:
      app: frontend-lab901 
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab901 
    spec:
      containers:
        - name: frontend-lab901 
          image: hooni26/frontend-lab901 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
