def label = "worker-${UUID.randomUUID().toString()}"
podTemplate(label: label, containers: [
containerTemplate(name: 'npm', image: 'node:lts', command: 'cat', ttyEnabled: true),
containerTemplate(name: "scanner", image: "newtmitch/sonar-scanner", ttyEnabled: true, command:"cat"),
containerTemplate(name: 'docker', image: 'docker:dind', command: 'dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay', ttyEnabled: true,alwaysPullImage: true, privileged: true),
containerTemplate(name: 'kubectl', image: 'roffe/kubectl', command: 'cat', ttyEnabled: true)
]) {
node(label) {
    // 예외처리 구문
	try {
		// Slack - 빌드 시작시

		// #1 Github 소스 가져오기
		stage('Get Source') {     git credentialsId: 'github-lab17', url: 'https://github.com/hooni26/cicd-front.git/', branch: 'master' } 
  } catch(e) {
		// Slack - 빌드 실패시

	}
}
}
